name: Build project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - name: Restore dependencies
      run: dotnet restore spa_src/SPA.sln
    - name: Build
      run: dotnet build spa_src/SPA.sln --no-restore --configuration Release
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
